query getBoard($id: ID) {
  board(id: $id) {
    id
    title
    order
    createdAt
    updatedAt
    image {
      id
      downloadUrl
    }
    tasks {
      items {
        id
        title
        description
        createdAt
        updatedAt
        dueAt
      }
    }
  }
}
